#!/bin/sh

# usage: input-file output-file start-time end-time

# input-file is the input video
# output-file is the name of the output file (should probably end with .gif if you want a gif file)
# start-time is the start of the gif
# end-time is the end of the gif

start_time=$3
end_time=$4

if [[ $start_time -eq no ]]; then
   echo "No start/end points defined; exiting..."
   exit 1
fi

duration=$(echo $end_time - $start_time | bc)

duration=$(printf '%f' $duration)

palette="/tmp/palette.png"

fps=$(ffmpeg -i "$1" 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p")

# filters="fps=$fps,scale=320:(320/(iw*sar))*ih:flags=lanczos" # uncomment this line and comment out the next one to force the output gif to a width of 320px.
filters="fps=$fps,scale=iw*sar:ih:flags=lanczos"

ffmpeg -v warning -ss $start_time -t $duration -i "$1" -vf "$filters,palettegen" -y $palette
ffmpeg -v warning -ss $start_time -t $duration -i "$1" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$2"
