#!/bin/sh

# usage: <gif|video> input-file output-dir start-time end-time

# input-file is the input video
# output-dir is the directory where you want to save the output file
# start-time is the start of the clip
# end-time is the end of the clip

start_time=$4
end_time=$5

if [[ "$start_time" == "no" || "$end_time" == "no" ]]; then
   echo "No start/end points defined; exiting..."
   exit 1
fi

duration=$(echo $end_time - $start_time | bc)

duration=$(printf '%f' $duration)

fps=$(ffmpeg -i "$2" 2>&1 | sed -n "s/.*, \(.*\) fp.*/\1/p")

# filters="fps=$fps,scale=320:(320/(iw*sar))*ih:flags=lanczos" # uncomment this line and comment out the next one to force a width of 320px.
filters="fps=$fps,scale=iw*sar:ih:flags=lanczos"

filename=$(echo $2 | sed "s/.*\/\(.*\)\..*$/\1/")

if [[ "$1" == "gif" ]]; then
    palette="/tmp/palette.png"
    ffmpeg -v warning -ss $start_time -t $duration -i "$2" -vf "$filters,palettegen" -y $palette
    ffmpeg -v warning -ss $start_time -t $duration -i "$2" -i $palette -lavfi "$filters [x]; [x][1:v] paletteuse" -y "$3/$filename $start_time.gif"
elif [[ "$1" == "video" ]]; then
    extension=$(echo $2 | sed "s/.*\.\(.*\)$/\1/")
    ffmpeg -v warning -ss $start_time -i "$2" -t $duration -vf "$filters" -y "$3/$filename $start_time.$extension"
else
    echo "First argument isn't \"gif\" or \"video\"; exiting..."
    exit 1
fi
